-- MySQL Script generated by MySQL Workbench
-- Mon Aug 15 20:43:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cypherrigs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cypherrigs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cypherrigs` DEFAULT CHARACTER SET utf8mb4 ;
USE `cypherrigs` ;

-- -----------------------------------------------------
-- Table `cypherrigs`.`asics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cypherrigs`.`asics` (
  `id_asic` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `precio` DECIMAL(24,0) NULL DEFAULT NULL,
  `especificaciones` VARCHAR(300) NULL DEFAULT NULL,
  `image` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id_asic`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cypherrigs`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cypherrigs`.`contacto` (
  `idcontacto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `asunto` VARCHAR(150) NULL DEFAULT NULL,
  `mensaje` VARCHAR(350) NULL DEFAULT NULL,
  PRIMARY KEY (`idcontacto`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cypherrigs`.`rigs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cypherrigs`.`rigs` (
  `id_rigs` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `precio` DECIMAL(24,0) NULL DEFAULT NULL,
  `especificaciones` VARCHAR(300) NULL DEFAULT NULL,
  `image` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rigs`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cypherrigs`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cypherrigs`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(400) NULL DEFAULT NULL,
  `rol` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
