-- MySQL Script generated by MySQL Workbench
-- Sat Aug 27 02:45:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cypherrigs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cypherrigs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cypherrigs` DEFAULT CHARACTER SET utf8mb4 ;
USE `cypherrigs` ;

-- -----------------------------------------------------
-- Table `cypherrigs`.`asics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cypherrigs`.`asics` (
  `id_asic` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `precio` DECIMAL(24,0) NULL DEFAULT NULL,
  `especificaciones` VARCHAR(300) NULL DEFAULT NULL,
  `image` VARCHAR(300) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `cartId` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` SMALLINT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_asic`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cypherrigs`.`buy_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cypherrigs`.`buy_history` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `comprador_id` INT(10) UNSIGNED NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `cypherrigs`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cypherrigs`.`categoria` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `especificaciones` VARCHAR(50) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cypherrigs`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cypherrigs`.`contacto` (
  `idcontacto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `asunto` VARCHAR(150) NULL DEFAULT NULL,
  `mensaje` VARCHAR(350) NULL DEFAULT NULL,
  PRIMARY KEY (`idcontacto`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cypherrigs`.`product_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cypherrigs`.`product_history` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `especificaciones` TEXT NULL DEFAULT NULL,
  `precio` FLOAT UNSIGNED NULL DEFAULT NULL,
  `cantidad` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `buy_history_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_buy_product_history_idx` (`buy_history_id` ASC) VISIBLE,
  CONSTRAINT `fk_buy_product_history`
    FOREIGN KEY (`buy_history_id`)
    REFERENCES `cypherrigs`.`buy_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `cypherrigs`.`rigs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cypherrigs`.`rigs` (
  `id_rigs` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `precio` DECIMAL(24,0) NULL DEFAULT NULL,
  `especificaciones` VARCHAR(300) NULL DEFAULT NULL,
  `image` VARCHAR(300) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `cartId` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` SMALLINT(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rigs`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cypherrigs`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cypherrigs`.`users` (
  `user_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `password` VARCHAR(400) NOT NULL,
  `rol` TINYINT(1) NOT NULL,
  `categoria` TINYINT(1) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
